### ISSUE TITLE
Add option to suppress the rule on certain file patterns

### ISSUE THREAD

**Issue by fabioimpe** [ArnaudBarre/eslint-plugin-react-refresh#10]
I'm working with Storybook and on stories files a default export is always required.
I don't want to clutter every file with the eslint disable rule comment, so it would be awesome to have an option to disable the rule for defined file patterns (eg. `*.stories.tsx`)

**Comment by ArnaudBarre** [comment]
Yeah just read the v6 et v7 doc for React, in both case an object export is required. So we can always skip analysing stories files. Available in v0.3.5
