### ISSUE TITLE
Consider all-uppercase exports as components

### ISSUE THREAD

**Issue by silverwind** [ArnaudBarre/eslint-plugin-react-refresh#11]
Why not consider uppercase exports as components? I for example have one like this:

```js
export function SVG() {
  return <svg/>;
}
```

It's mostly stylistic, but a `Svg` looks suboptimal to me.

Another idea may be that such a component could just be automatically detected as one because it returns JSX content, e.g. don't purely rely on export name, but actually analyze the return value of the function.

**Comment by ArnaudBarre** [comment]
Added in [0.4.1](https://github.com/ArnaudBarre/eslint-plugin-react-refresh/releases/tag/v0.4.1)

(I've decided to not use type analysis because this could block a lot of people (not the default with TS-ESLint), so I need to add cases one by one)
