### ISSUE TITLE
Allow `export type * from '...'`

### ISSUE THREAD

**Issue by basicdays** [ArnaudBarre/eslint-plugin-react-refresh#12]
Hey there,

I'm not familiar enough with `react-refresh`, but I'm guessing that purely type exports from a `tsx` file wouldn't impact it at all. Would it be possible to allow the `export type * from "./module";` as an optional rule? This is convenient when making things like hook files to re-export types for quality of life purposes.

You can see more about it here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#support-for-export-type-

**Comment by ArnaudBarre** [comment]
Yeah type export are not present at runtime so they can safely be ignore. This is simple to add if eslint has already support for this in the AST. I'm looking into it

**Comment by ArnaudBarre** [comment]
Available in [0.4.1](https://github.com/ArnaudBarre/eslint-plugin-react-refresh/releases/tag/v0.4.1)
