### ISSUE TITLE
Warning triggered for component using forwardRef

### ISSUE THREAD

**Issue by hichemfantar** [ArnaudBarre/eslint-plugin-react-refresh#13]
v0.41
I get this error when calling React.forwardRef on my component.
```js
function CardContainer(props,ref) {
	return <div ref={ref}>Hello world!</div>;
}

export default forwardRef(CardContainer);
```

**Comment by ArnaudBarre** [comment]
Yep that's normal because you export an anonymous component which is not recommended because this will not be available in devtools and stack traces.

```tsx
function InnerCardContainer(props,ref) {
	return <div ref={ref}>Hello world!</div>;
}

export const CardContainer = forwardRef(InnerCardContainer);
```

**Comment by hichemfantar** [comment]
Understandable, thanks for the clarification.

**Comment by hichemfantar** [comment]
One more thing @ArnaudBarre , you said the component will not be available in devtools and stack traces yet the component appears normally in the devtools and in the profiler.
examples below:
![image](https://github.com/ArnaudBarre/eslint-plugin-react-refresh/assets/34947993/82e1d1c7-188b-4357-93f9-d6f8ca56226e)
![image](https://github.com/ArnaudBarre/eslint-plugin-react-refresh/assets/34947993/da031584-798b-4229-8ddf-3a342e49f5dc)

**Comment by ArnaudBarre** [comment]
Interesting, I never really tested this fact from the React team because for me there is a good reason to name you component and ban default export: https://jamie-wong.com/2013/07/12/grep-test/

**Comment by hichemfantar** [comment]
Thanks for the article, that was a good read.
I ended up using this syntax to avoid renaming the function.
```js
const CardContainer = forwardRef(function CardContainer(props,ref) {
	return <div ref={ref}>Hello world!</div>;
})

export default CardContainer;
```

**Comment by ArnaudBarre** [comment]
That could be a challenging refactor, but I advice you to move to `export const CardContainer`. On top of being simpler to write, it's more align with what I do in other files where I can export a bunch of functions, contants and so on.
The default export add a barrier to export multiple React component in the same file, which I used often when there are 2-3 small components related to each other

**Comment by hichemfantar** [comment]
Named exports is definitely more convenient and easier to follow.
I'm currently slowly refactoring default exports to named exports and I'm def noticing improvements.
Thanks for the tips, I'm slowly incorporating them into my current project.
