### ISSUE TITLE
Warning is not appearing for enums

### ISSUE THREAD

**Issue by RakhmatovR** [ArnaudBarre/eslint-plugin-react-refresh#19]
Hello,

I have an exported component with an exported enum in one file, but I do not get a ESLint warning. But I do get a warning if I add an exported string into file. Shouldn't the enum be highlighted with error as well?

<details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/ArnaudBarre/eslint-plugin-react-refresh/assets/12181701/f929b4e5-492d-42c3-a014-228b6a5aac7c)
</details>

Thanks

**Comment by ArnaudBarre** [comment]
Thanks for the report, fixed in 0.4.3!
