### ISSUE TITLE
Fast Refresh and Hooks

### ISSUE THREAD

**Issue by waynebloss** [ArnaudBarre/eslint-plugin-react-refresh#20]
Hello. This plugin triggers a warning when my file exports a component and a related hook. However, I have read that [fast refresh works with components and hooks](https://nextjs.org/docs/architecture/fast-refresh#fast-refresh-and-hooks).

Is this a bug in the plugin or am I missing some other information?

Thanks.

**Comment by ArnaudBarre** [comment]
It says that hooks state inside components is preserved, not that exporting hooks aside component is supported.
