### ISSUE TITLE
Add option for allowList of export names

### ISSUE THREAD

**Issue by aaronadamsCA** [ArnaudBarre/eslint-plugin-react-refresh#29]
Remix adds [special handling of specific named exports](https://remix.run/docs/en/main/other-api/dev#:~:text=React%20Fast%20Refresh%20can%20only%20handle%20component%20exports.%20While%20Remix%20manages%20special%20route%20exports%20like%20meta%2C%20links%2C%20and%20header%20for%20you%2C%20any%20user%2Ddefined%2C%20will%20cause%20full%20reloads%3A) to make them work with Fast Refresh.

I'd like to be able to pass this plugin a config like `{ allowExportNames: ["meta", "links", "headers", "loader", "action"] }` so I can make sure my Remix route components are compatible with Fast Refresh.

**Comment by ArnaudBarre** [comment]
Cool to this that!
I will work on that this week!

**Comment by ArnaudBarre** [comment]
Released in v0.4.4

**Comment by aaronadamsCA** [comment]
Thank you, it works perfectly! 🎉
