### ISSUE TITLE
Question about potential problems with barrel files

### ISSUE THREAD

**Issue by kylemh** [ArnaudBarre/eslint-plugin-react-refresh#37]
Hello! This isn't really an issue. Just a question...

<img width="826" alt="Screenshot 2024-02-15 at 8 51 32 PM" src="https://github.com/ArnaudBarre/eslint-plugin-react-refresh/assets/9523719/c54d92ee-a6df-4544-8a16-c8be372f3e01">

I've got a monorepo with a `ui` package that exports hooks, utils, and components.

We export this by doing a barrel file for all hooks, all utils, and components... then we do one package-level barrel-file that exports all the contents of the 3 other barrel files. That top-level barrel file is marked as `main` and `types` in the `ui` package's `package.json`. Then, I symlink the package as via installing it in other monorepo applications like:

`"@scoped/ui": "workspace:*"`

Am I potentially hurting fast refresh for the applications with this setup?

**Comment by ArnaudBarre** [comment]
If you rename the file to `index.ts` it will be fine!
