### ISSUE TITLE
Modern eslint.config.js support

### ISSUE THREAD

**Issue by yy-do-it** [ArnaudBarre/eslint-plugin-react-refresh#42]
It would've been nice if react-refresh plugin would support new es module config.

![зображення](https://github.com/ArnaudBarre/eslint-plugin-react-refresh/assets/167980386/483b2e84-7f8f-4225-baa1-791e1c3b1e91)

**Comment by Kiyozz** [comment]
To use this plugin (v0.4.6), I had to use @eslint/eslintrc package for eslintrc config format compatibility.

**Comment by ArnaudBarre** [comment]
I tested again and the from the documentation is working, probably you forgot to add `'react-refresh': reactRefresh,` to the plugins object.

**Comment by Kiyozz** [comment]
My bad, I meant "react-hooks" not react-refresh! Wrong repo
