### ISSUE TITLE
Type exports should be ignored

### ISSUE THREAD

**Issue by silverwind** [ArnaudBarre/eslint-plugin-react-refresh#47]
In TypeScript, a type export currently triggers `react-refresh/only-export-components`:

```ts
type foo = string;
export const Foo = () => null;
export type {foo}; // error: Fast refresh only works when a file only exports components. Use a new file to share constants or functions between components.
```

As far as I understand, type aliases have no runtime behaviour and therefor should not prevent fast refresh.

**Comment by ArnaudBarre** [comment]
Funny I though I exclude them but never ran into it because types often follow PascalCase naming convention

**Comment by silverwind** [comment]
Yeah, my own types are always PascalCase too, but in this case I was re-exporting a lowercase type from another module.
