### ISSUE TITLE
How can I prevent eslint error in Next.js's getServerSideProps?

### ISSUE THREAD

**Issue by zebra0303** [ArnaudBarre/eslint-plugin-react-refresh#49]
Hello, I'm trying to use the eslint-plugin-react-refresh rule for a team project.
However, an eslint error occurs even when exporting getServerSideProps in the page component of Next.js. 
Is there anyone who has solved this issue or knows a solution without creating a new getServerSideProps function file?

[package.json]
```json
"eslint-plugin-react-refresh": "^0.4.11",
```
[ESLint Config]
```javascript
'react-refresh/only-export-components': ['error', { allowConstantExport: true }],
```
[Page Code Sample]
```typescript
import type { InferGetServerSidePropsType, GetServerSideProps } from 'next';

interface Repo {
  name: string;
  stargazers_count: number;
}

// Here is an eslint error !!!
// Fast refresh only works when a file only exports components. 
// Use a new file to share constants or functions between components.eslint(react-refresh/only-export-components)
export const getServerSideProps = (async () => {
  const res = await fetch('https://api.github.com/repos/vercel/next.js');
  const repo: Repo = await res.json();

  return { props: { repo } };
}) satisfies GetServerSideProps<{ repo: Repo }>;

export default function Page({ repo }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <main>
      <p>{repo.stargazers_count}</p>
    </main>
  );
}
```

**Comment by ArnaudBarre** [comment]
I never tried but using https://github.com/ArnaudBarre/eslint-plugin-react-refresh?tab=readme-ov-file#allowexportnames-v044 with `["getServerSideProps"]` should works?

**Comment by zebra0303** [comment]
> I never tried but using https://github.com/ArnaudBarre/eslint-plugin-react-refresh?tab=readme-ov-file#allowexportnames-v044 with `["getServerSideProps"]` should works?


@ArnaudBarre, Thanks for your reply. It works fine after I changed the plugin options as below.
```javascript
   'react-refresh/only-export-components': [
      'warn',
      {
        allowConstantExport: true,
        allowExportNames: ['getServerSideProps'],
      },
    ],
```
