### ISSUE TITLE
Doesn't support Arbitrary Module Identifiers in TypeScript 5.6

### ISSUE THREAD

**Issue by pauliesnug** [ArnaudBarre/eslint-plugin-react-refresh#52]
In `typescript-eslint@v8.10.0`, they added support for `ExportNamedDeclaration`s having children string literals, due to the 5.6 change of [arbitrary module identifiers](https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#support-for-arbitrary-module-identifiers). These probably aren't supported by HMR anyway, so should they just throw an error? Right now when building for the `v8.10.0`, it will throw an error.

**Comment by ArnaudBarre** [comment]
Thanks for letting me know, I look into it!
