### ISSUE TITLE
Crash while linting after upgrading to 0.4.14

### ISSUE THREAD

**Issue by bobdepreziz** [ArnaudBarre/eslint-plugin-react-refresh#56]
Hello,

I noticed a crash while linting after updating to version 0.4.14.

TypeError: Error while loading rule 'react-refresh/only-export-components': Cannot read properties of undefined (reading 'includes')
Occurred while linting /Users/bobd/mf-react-track-and-trace/lib/index.ts
    at Object.create (/Users/bobd/mf-react-track-and-trace/node_modules/eslint-plugin-react-refresh/index.js:63:18)
    at createRuleListeners (/Users/bobd/mf-react-track-and-trace/node_modules/eslint/lib/linter/linter.js:765:21)

If I look at where this comes from  I see it is this includes on filename:

![Screenshot 2024-10-29 at 14 54 29](https://github.com/user-attachments/assets/38f73b81-1358-49bc-a040-f0a503b8bf07)

I see that has been changed in this merge request:
https://github.com/ArnaudBarre/eslint-plugin-react-refresh/pull/54/files

Is this a bug on your end or are we doing something wrong configuration wise, with version 0.4.13 there are no issues.

**Comment by ArnaudBarre** [comment]
Oh yeah this changed bumped the implicit required peer version for ESLint to `v8.40`. This was not expected. If you bump ESLint to at least 8.40 it should be ok. I will update the code to be more backward compatible in the next release
