### ISSUE TITLE
Will this be updated for eslint 9 and the new flat format?

### ISSUE THREAD

**Issue by geoff-harper** [ArnaudBarre/eslint-plugin-react-refresh#57]
Just checking in since I don't believe this is eslint v9 compatible.

**Comment by ArnaudBarre** [comment]
It is, I should put the flat config first in the doc now: https://github.com/ArnaudBarre/eslint-plugin-react-refresh?tab=readme-ov-file#flat-config

**Comment by geoff-harper** [comment]
and there it is, cheers
