### ISSUE TITLE
 Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by Jupiter-u** [ArnaudBarre/eslint-plugin-react-refresh#58]
![image](https://github.com/user-attachments/assets/b91379bf-ddca-41d9-ab39-a6ce447e27b1)
突然之间报这个错误，求大佬帮忙看下什么原因，之前好好的，刚刚跑项目页面加载不出来看控制台报这个错误

**Comment by ArnaudBarre** [comment]
This code does not run the browser so the issue doesn't come from this plugin. Please provide more context and translate it to english when reporting issues.
