### ISSUE TITLE
After updating to 0.4.15, plugin stopped working

### ISSUE THREAD

**Issue by rakleed** [ArnaudBarre/eslint-plugin-react-refresh#68]
When using the `reactRefresh.configs.recommended` or `reactRefresh.configs.vite` config, I get a `Cannot read properties of undefined (reading 'recommended')` or '`Cannot read properties of undefined (reading 'vite')`' error.

Reproduction: https://eslint-online-playground.netlify.app/#eNp9kctOwzAQRX/F8qYgNU7DS1BUNvAFbAlIUTwJBnts2U5VVOXf8UulQtBFIktz7pnxeE+d7WvYdcpIYB+OrinsjLae9BqdJ49aGY2AnmzI2TnZPJB9i4RY8JNFgpOU9y3O4aNLCk4K9CwEBzFmlwjp4LLQ9f4ZBgvunQxWK7LIcGXkNAqsEhD+iVgEXYtlDA5DN0lPXnLbH0/p45iFXisFyIEvI1TXf3Nb4SEAr3lY0/Wf3RivrDEMmm7VUv9loKXrcFKaTzKck7KlHEzsgL0AF4HEx0JqlSNvzS27ZE3JHIoV1+oXEOvzwbx9+k+el1TCd6y5Yasj+4kVlsiKXbHm+igSd1BqwcUuyijhCen8DT+Zqqs=

**Comment by rakleed** [comment]
Hmm, but the previously used method also stopped working (`Key "rules": Key "react-refresh/only-export-components": Could not find "only-export-components" in plugin "react-refresh".` error), now the plugin doesn’t work at all: https://eslint-online-playground.netlify.app/#eNp9kt9OgzAYxV/lS680Gd3wXxQzb/QJvLUuIfCBaPnatGXZsvDulraYbYm7oITknN85HDgwa6ol7speS+TflhUMd1oZB5Ui6+BV9VoRkoM1XF3D+gUOggAMusEQ0CDls6DRX2zB0MqOHPfGpmsjq/NuzzJYVu4dG4P2CxqjehBJnWk5tB1lQeHPIBHMAwWlIjU25SAdfEzBIR0gumwxP4MHniGKk9RF1I3pbgaJF9xLRXKfxfysmiewE9QXN0YZwU6I0/kZV9Bl9VO205aK/AIhQjC31xjtvap9ePILVqNGqpGqDgM/VUqFomWTP/Jbnv9lzm1r1Z8J5i6RvH37Dx7HT+Ynnj/w1RH94qcJlhW/4/n9kWXbufR+G8/iN6mK/zfY+AvNncQc

**Comment by anthonyhastings-eqs** [comment]
Looks to be exporting only a CommonJS build and not an ESM one

**Comment by RebeccaStevens** [comment]
```js
console.log(await import("eslint-plugin-react-refresh"));
// => [Module: null prototype] { default: { default: [Getter] } }
```

Well, there's the issue, an extra nested `default`.

**Comment by mikroware** [comment]
> Well, there's the issue, an extra nested `default`.

Indeed, using `reactRefreshPlugin.default.configs.vite` seems to work for me.

**Comment by ArnaudBarre** [comment]
Reverted the bad change in 0.4.16. Sorry for the trouble.
