### ISSUE TITLE
Is this library for both React and React Native?

### ISSUE THREAD

**Issue by hongbo-miao** [ArnaudBarre/eslint-plugin-react-refresh#72]
Is this library for both React and React Native?

Based on readme, seems it is for React only. But I saw this conversation at https://github.com/ArnaudBarre/eslint-plugin-react-refresh/issues/28 which can also be React Native? Am I correct? Thanks!

**Comment by ArnaudBarre** [comment]
Fast refresh is also used in RN, but I don't know how metro, the default RN bundler, handle this. I saw some people succeded to make Vite works with RN, in that case this rules will have a big impact on HMR speed.

**Comment by hongbo-miao** [comment]
I see, thank you for clarifying, @ArnaudBarre ! 😃
